[package]
name = "firewallapp"
version = "0.4.2"
authors = ["mvclaudianobj <mvclaudiano@gmail.com>"]
edition = "2023"
description = "FirewallApp: Use MITM technology to provide features like rewrite, redirect."
homepage = "https://github.com/mvclaudianobj/firewallapp"
repository = "https://github.com/mvclaudianobj/firewallapp"
license = "MIT"

[dependencies]
async-trait = "0.1"
bytes = { version = "1", features = ["serde"] }
cfg-if = "1"
http = "0.2"
hyper = { version = "0.14", features = ["http1", "http2", "server", "stream", "tcp", "runtime"]  }
hyper-proxy = { version = "0.9" }
hyper-rustls = { version = "0.24" }
hyper-tls = { version = "0.5", optional = true }
log = "0.4"
moka = { version = "0.11", features = ["future"] }
openssl = { version = "0.10", features = ["vendored"], optional = true }
rcgen = { version = "0.10", features = ["x509-parser"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1"
time = "0.3"
typed-builder = "0.14"
tokio = { version = "1", features = ["rt"] }
tokio-rustls = { version = "0.24", default-features = false, features = ["tls12"] }
tokio-util = { version = "0.7", features = ["io"] }
wildmatch = "2.1"
rustls = { version = "0.21", features = ["dangerous_configuration"] }
rand = "0.8"

[features]
default = ["h2", "request-native-tls"]
request-native-tls = ["hyper-tls", "openssl"]
h2 = ["hyper-rustls/http2"]
